# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

default: &default
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

development:
  <<: *default
  secret_key_base: 1385053c290c851fe12820cee7907d89836824d4e495d3aec2d35f6c6c437c8a1f252a09a375522eed824fe0c2c909e7f95383a594dbf6fec79a6dc2565319ee

test:
  <<: *default
  secret_key_base: f3b98c3d62a32721f46562843f43a55ba2432445d6a89bbc54bd3d99276da93f40e1354821c3f69e6f65b238c694289318025235c04e1e61c6484e259bcaa861

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
